### ISSUE TITLE
Hardcoded filepath breaking workflow

### ISSUE THREAD

**Issue by dpgil** [rniemo/Heroes-Predictor#1]
hi all,

just wanted to say I love using this product. really enjoy it. it's great! really. 

there seems to be one minor issue however that makes it difficult to use. it seems there's a hardcoded filepath to the replays data (https://github.com/rniemo/Heroes-Predictor/blob/master/Predictor/Predictor/Program.cs#L166). unfortunately the files on my device are not structured like this. that was the folder where I stored videos of my child speaking her first word and every piano recital she's ever performed. I deleted them to work around the issue, but just curious are there plans to allow for custom filepaths in the future?

thx a million
dan

**Comment by dpgil** [comment]
@rniemo since you seem to be the top contributor on this product

**Comment by rniemo** [comment]
hi dan,

We won't be able to support this request for a few reasons.
- first and foremost, retaining your (or anyone's) child's precious memories isn't a goal of the project. everyone needs to make hard choices in life, and, frankly, the choice between children's memories and our software is not one of them. we'll choose our software every day of the week.
- there are higher priority items in our queue, like leaving snarky comments on other people's projects.

thanks for using the #1 predictor for the #1 moba on the market.

you're welcome one billion
ryan
